"""Domains, mailboxes and aliases.

Postfix and Dovecot query these tables directly via read-only SQL maps
(see compose/postfix/pgsql-*.cf and compose/dovecot/dovecot-sql.conf.ext),
so creating a Mailbox row makes the address live immediately.
"""
from django.conf import settings
from django.db import models


class Domain(models.Model):
    name = models.CharField(max_length=255, unique=True)
    dkim_selector = models.CharField(max_length=63, default="mail")
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name


class Mailbox(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="mailboxes"
    )
    domain = models.ForeignKey(Domain, on_delete=models.PROTECT)
    local_part = models.CharField(max_length=64)
    # Dovecot-compatible hash with scheme prefix, e.g. "{ARGON2ID}$argon2id$...".
    # Generated by accounts.services.dovecot_hash(); never store plaintext.
    password_hash = models.CharField(max_length=512)
    maildir_path = models.CharField(max_length=512, editable=False)
    quota_mb = models.PositiveIntegerField(default=2048)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("domain", "local_part")
        verbose_name_plural = "mailboxes"

    @property
    def address(self) -> str:
        return f"{self.local_part}@{self.domain.name}"

    def save(self, *args, **kwargs):
        if not self.maildir_path:
            self.maildir_path = f"/var/vmail/{self.domain.name}/{self.local_part}/"
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.address


class Alias(models.Model):
    domain = models.ForeignKey(Domain, on_delete=models.CASCADE)
    # source="" means catch-all for the domain.
    source = models.CharField(max_length=64, blank=True)
    destination = models.EmailField()
    active = models.BooleanField(default=True)

    class Meta:
        unique_together = ("domain", "source", "destination")
        verbose_name_plural = "aliases"

    def __str__(self) -> str:
        src = self.source or "*"
        return f"{src}@{self.domain.name} -> {self.destination}"


class AppPassword(models.Model):
    """Per-device passwords for IMAP clients when the account uses 2FA.

    The webmail logs in with Django credentials + OTP; native IMAP clients
    use one of these instead of the primary password.
    """
    mailbox = models.ForeignKey(Mailbox, on_delete=models.CASCADE, related_name="app_passwords")
    label = models.CharField(max_length=64)  # "Phone", "Thunderbird", ...
    password_hash = models.CharField(max_length=512)
    created_at = models.DateTimeField(auto_now_add=True)
    last_used_at = models.DateTimeField(null=True, blank=True)
